<!doctype html>
<html lang="en">
<head>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 
<!-- jQuery UI -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
 
<!-- Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
* {
  box-sizing: border-box;
}

body {
  font: 16px Arial;  
}

/*the container must be positioned relative:*/
.autocomplete {
  
  position: relative;
  display: inline-block;
}

input {
  border: 1px solid transparent;
  background-color: #f1f1f1;
  padding: 10px;
  font-size: 16px;
}

input[type=text] {
  background-color: #f1f1f1;
  width: 100%;
}

input[type=submit] {
  background-color: DodgerBlue;
  color: #fff;
  cursor: pointer;
}


</style>

</head>

<body>


<p>Tag Search:</p>

<!--Make sure the form has the autocomplete function switched off:-->
  <div class="autocomplete" style="width:300px;"  >
    <input id = "search_tag" type="text" >
  </div>
  <input type="submit" id = "search_problem">

  <table align = "center"
            id="table" border="1"> 
    </table> 
    <strong> 
      <span id = "result">

      </span> 
    </strong>



<script type="text/javascript">

    $( "#search_tag" ).autocomplete({source: '/tags/search'});
 
    $("#search_problem").click(function(){
        $.get( "/problem/search",{term: $("#search_tag").val() }, function( data ) {
          if ( data['status_code'] == 404 ) {
            $("#table tr").remove();
            $('#result').replaceWith('<span id = "result">'+ "Please enter the valid tag" + '</span>');
          }
          else{
            $("#table tr").remove();
            list = data['problems'];
            $('#result').replaceWith('<span id = "result"> </span>');
            constructTable("#table");
          }
            function constructTable(selector) { 
              
              // Getting the all column names 
              var cols = Headers(list, selector);   
     
              // Traversing the JSON data 
              for (var i = 0; i < list.length; i++) { 
                  var row = $('<tr/>');    
                  for (var colIndex = 0; colIndex < cols.length; colIndex++) 
                  { 
                      var val = list[i][cols[colIndex]];
                      var str1 =  cols[colIndex];
                      var str2  = "Problem Code"
                        if(str1.localeCompare(str2)==0){
                            var dm = "<a href = https://www.codechef.com/problems/" + val + " target='_blank' > " + val + " </a>" 
                        // If there is any key, which is matching 
                        // with the column name 
                        if (val == null) val = "";   
                            row.append($('<td/>').html(dm)); 
                        }
                        else{
                            if (val == null) val = "";   
                            row.append($('<td/>').html(val));
                        }
                      
                  } 
                    
                  // Adding each row to the table 
                  $(selector).append(row); 
              } 
          } 
            
          function Headers(list, selector) { 
              var columns = []; 
              var header = $('<tr/>'); 
                
              for (var i = 0; i < list.length; i++) { 
                  var row = list[i]; 
                    
                  for (var k in row) { 
                      if ($.inArray(k, columns) == -1) { 
                          columns.push(k); 
                            
                          // Creating the header 
                          header.append($('<th/>').html(k)); 
                      } 
                  } 
              } 
                
              // Appending the header to the table 
              $(selector).append(header); 
                  return columns; 
          }
        
        });
    });

    
         

</script>

</body>
</html>